### ISSUE TITLE
LD(label, Rc) emits incorrect instructions

### ISSUE THREAD

**Issue by kaine119** [natalieagus/beta-assembler#1]
The Beta ISA spec defines `LD(label, Rc)` as a convenience macro for `LD(R31, label, Rc)`. However, the instruction emitted when using this macro doesn't match the regular instruction:

| Assembly          | Emitted instruction | Opcode |  Rc | Ra | literal |
| -----------------|-------------------|-----------|---|-----|-------|
| `LD(inputs, R1)` | `h63e00001`      | 0x18 | R31 | R0 | 0x1 |
| `LD(R31, inputs, R1)` | `h603f0800` | 0x18 | R1 | R31 | 0x800 |

(where `inputs = 0x800`)

**Comment by natalieagus** [comment]
Closed as c61e17a067bf77cb30a7d4cf658fe992cd3ca7d9

**Comment by natalieagus** [comment]
closed as c61e17a067bf77cb30a7d4cf658fe992cd3ca7d9
